name:                the-haskell-book
version:             0.1.0.0
github:              "thinkmpink/the-haskell-book"
license:             BSD3
author:              "Michael Pinkham"
maintainer:          "mpinkham3@gmail.com"
copyright:           "Michael Pinkham 2017"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thinkmpink/the-haskell-book#readme>

dependencies:
- base >= 4.7 && < 5
- random
- transformers
- time
- hspec
- checkers
- trifecta
- raw-strings-qq

library:
  source-dirs: src
  dependencies: QuickCheck

executables:
  the-haskell-book-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-haskell-book

tests:
  the-haskell-book-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-haskell-book
    - QuickCheck
